### ISSUE TITLE
Отсутствует запрос на выброс IllegalArgumentException при создании объекта класса SavingAccount  при отрицательном initialBalance 

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#11]
# Описание
Конструктор класса SaveAccount не содержит проверки параметра initialBalance на отрицательные значения.

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с параметрами, где initialBalance отрицательно число:
  `initialBalance = -100, minBalance = 200, maxBalance = 10_000, rate = 15` 
 
*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException.
*Фактический результат:* Объект класса SavingAccount успешно создан с отрицательным значением initialBalance.

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L81

**Comment by stasechka11** [comment]
Исправлено [8fa1be10a6b32112a44fd861df69d5d079a17854](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
