### ISSUE TITLE
Отсутствует запрос на выброс IllegalArgumentException при создании объекта класса SavingAccount при отрицательном минимальном балансе minBalance

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#12]
# Описание
Конструктор класса SavingAccount не содержит проверки параметра minBalance на отрицательное значение. 

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/2d5312a1e567e97e50483718988451335894e42d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с отрицательным параметром minBalance   :
  `initialBalance = 1_000; 
   minBalance = -200;
 maxBalance = 10000;
  rate = 15.` 
 
*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException.
*Фактический результат:* Объект класса SavingAccount успешно создан с отрицательным значением минимального баланса(minBalance).

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L53

**Comment by stasechka11** [comment]
Исправлено [8fa1be10a6b32112a44fd861df69d5d079a17854](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
