### ISSUE TITLE
Отсутствует запрос на выброс IllegalArgumentException при превышении минимального баланса над максимальным при создании объекта класса SavingAccount 

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#13]
# Описание
Конструктор класса SavingAccount не содержит проверки превышения  минимального баланса(minBalance) над максимальным(maxBalance) при создании счета. 

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/2d5312a1e567e97e50483718988451335894e42d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с параметром  rate = 0 :
  `initialBalance = 1_000; 
   minBalance = 20_000;
 maxBalance = 9_000;
  rate = 15.` 
 
*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException.
*Фактический результат:* Объект класса SavingAccount успешно создан с параметрами minBalance 20_000 и maxBalance=9_000.

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L98

**Comment by stasechka11** [comment]
Исправлено [8fa1be1](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
