### ISSUE TITLE
Отсутствует запрос на выброс IllegalArgumentException на отрицательный максимальный баланс при создании объекта класса SavingAccount 

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#15]
# Описание
Конструктор класса SavingAccount не содержит проверки параметра maxBalance на отрицательное значение. 

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/2d5312a1e567e97e50483718988451335894e42d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с параметром  maxBalance = -100 :
  `initialBalance = 100; 
   minBalance = 100;
 maxBalance = -100;
  rate = 15.` 
 
*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException.
*Фактический результат:* Объект класса SavingAccount успешно создан с заданным параметром maxBalance.

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L123

**Comment by stasechka11** [comment]
Исправлено [8fa1be10a6b32112a44fd861df69d5d079a17854](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
