### ISSUE TITLE
Операция расчета процентов на остаток создает отрицательный процент в при создании объекта класса SavingAccount

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#17]
# Описание
Метод _**yearChange()**_ класса SavingAccount не содержит проверки параметра balance на отрицательное значение. Создает отрицательное значение ставки на сберегательный счет.

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с параметрами :
  `initialBalance = -100; 
   minBalance = 100;
 maxBalance = 3500;
  rate = 15.` 
 
*Ожидаемый результат:* Возврат значения _False_.
*Фактический результат:* Объект класса SavingAccount успешно создан с отрицательной ставкой (rate=-15).

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/ef8846f0cc87371093a78bf2c3b96aadec281fee/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L297

**Comment by stasechka11** [comment]
Исправлено [8fa1be10a6b32112a44fd861df69d5d079a17854 ](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
