### ISSUE TITLE
Отсутствует запрос на выброс IllegalArgumentException при нулевом значении ставки при создании объекта класса SavingAccount 

### ISSUE THREAD

**Issue by Testogeo** [stasechka11/javaqa-team-diplom-2#6]
# Описание
Конструктор класса SavingAccount не содержит проверки параметра rate на нулевое значение. 

# Локация дефекта
https://github.com/stasechka11/javaqa-team-diplom-2/blob/2d5312a1e567e97e50483718988451335894e42d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/stasechka11/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект класса SavingAccount с параметром  rate = 0 :
  `initialBalance = 1000; 
   minBalance = 200;
 maxBalance = 10000;
  rate = 0.` 
 
*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException.
*Фактический результат:* Объект класса SavingAccount успешно создан с нулевым значением ставки (rate).

# Тест
https://github.com/stasechka11/javaqa-team-diplom-2/blob/93b3c1e6b7e9004e3ba2cb373f615a3a285336a3/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L39

**Comment by stasechka11** [comment]
Исправлено [8fa1be10a6b32112a44fd861df69d5d079a17854](https://github.com/stasechka11/javaqa-team-diplom-2/commit/8fa1be10a6b32112a44fd861df69d5d079a17854)
